# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_member.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(601, 194)
        self.fioEdit = QtWidgets.QLineEdit(Dialog)
        self.fioEdit.setGeometry(QtCore.QRect(60, 10, 521, 24))
        self.fioEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.fioEdit.setInputMask("")
        self.fioEdit.setMaxLength(32767)
        self.fioEdit.setObjectName("fioEdit")
        self.fioLabel = QtWidgets.QLabel(Dialog)
        self.fioLabel.setGeometry(QtCore.QRect(20, 12, 41, 20))
        self.fioLabel.setObjectName("fioLabel")
        self.dateLabel = QtWidgets.QLabel(Dialog)
        self.dateLabel.setGeometry(QtCore.QRect(20, 42, 111, 20))
        self.dateLabel.setObjectName("dateLabel")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(130, 40, 110, 24))
        self.dateEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.dateEdit.setObjectName("dateEdit")
        self.sexLabel = QtWidgets.QLabel(Dialog)
        self.sexLabel.setGeometry(QtCore.QRect(250, 42, 31, 20))
        self.sexLabel.setObjectName("sexLabel")
        self.sexCBox = QtWidgets.QComboBox(Dialog)
        self.sexCBox.setGeometry(QtCore.QRect(290, 40, 131, 24))
        self.sexCBox.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.sexCBox.setObjectName("sexCBox")
        self.weightLabel = QtWidgets.QLabel(Dialog)
        self.weightLabel.setGeometry(QtCore.QRect(20, 72, 71, 20))
        self.weightLabel.setObjectName("weightLabel")
        self.categoryLabel = QtWidgets.QLabel(Dialog)
        self.categoryLabel.setGeometry(QtCore.QRect(430, 42, 51, 20))
        self.categoryLabel.setObjectName("categoryLabel")
        self.trainerLabel = QtWidgets.QLabel(Dialog)
        self.trainerLabel.setGeometry(QtCore.QRect(20, 102, 51, 20))
        self.trainerLabel.setObjectName("trainerLabel")
        self.trainerEdit = QtWidgets.QLineEdit(Dialog)
        self.trainerEdit.setGeometry(QtCore.QRect(80, 100, 501, 24))
        self.trainerEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.trainerEdit.setObjectName("trainerEdit")
        self.regionLabel = QtWidgets.QLabel(Dialog)
        self.regionLabel.setGeometry(QtCore.QRect(20, 130, 59, 20))
        self.regionLabel.setObjectName("regionLabel")
        self.regionEdit = QtWidgets.QLineEdit(Dialog)
        self.regionEdit.setGeometry(QtCore.QRect(80, 130, 231, 24))
        self.regionEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Rundi, QtCore.QLocale.Burundi))
        self.regionEdit.setObjectName("regionEdit")
        self.cityLabel = QtWidgets.QLabel(Dialog)
        self.cityLabel.setGeometry(QtCore.QRect(320, 132, 41, 20))
        self.cityLabel.setObjectName("cityLabel")
        self.cityEdit = QtWidgets.QLineEdit(Dialog)
        self.cityEdit.setGeometry(QtCore.QRect(370, 130, 211, 24))
        self.cityEdit.setObjectName("cityEdit")
        self.clubLabel = QtWidgets.QLabel(Dialog)
        self.clubLabel.setGeometry(QtCore.QRect(360, 70, 40, 20))
        self.clubLabel.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.clubLabel.setObjectName("clubLabel")
        self.clubEdit = QtWidgets.QLineEdit(Dialog)
        self.clubEdit.setGeometry(QtCore.QRect(400, 70, 181, 24))
        self.clubEdit.setLocale(QtCore.QLocale(QtCore.QLocale.Russian, QtCore.QLocale.Russia))
        self.clubEdit.setObjectName("clubEdit")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(500, 160, 79, 24))
        self.cancelButton.setObjectName("cancelButton")
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(410, 160, 79, 24))
        self.addButton.setObjectName("addButton")
        self.weightcatCBox = QtWidgets.QComboBox(Dialog)
        self.weightcatCBox.setGeometry(QtCore.QRect(100, 70, 251, 24))
        self.weightcatCBox.setObjectName("weightcatCBox")
        self.updateButton = QtWidgets.QPushButton(Dialog)
        self.updateButton.setGeometry(QtCore.QRect(410, 160, 79, 24))
        self.updateButton.setObjectName("updateButton")
        self.categoryCBox = QtWidgets.QComboBox(Dialog)
        self.categoryCBox.setGeometry(QtCore.QRect(490, 40, 91, 24))
        self.categoryCBox.setObjectName("categoryCBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.fioEdit, self.dateEdit)
        Dialog.setTabOrder(self.dateEdit, self.sexCBox)
        Dialog.setTabOrder(self.sexCBox, self.categoryCBox)
        Dialog.setTabOrder(self.categoryCBox, self.weightcatCBox)
        Dialog.setTabOrder(self.weightcatCBox, self.clubEdit)
        Dialog.setTabOrder(self.clubEdit, self.trainerEdit)
        Dialog.setTabOrder(self.trainerEdit, self.regionEdit)
        Dialog.setTabOrder(self.regionEdit, self.cityEdit)
        Dialog.setTabOrder(self.cityEdit, self.addButton)
        Dialog.setTabOrder(self.addButton, self.cancelButton)
        Dialog.setTabOrder(self.cancelButton, self.updateButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.fioLabel.setText(_translate("Dialog", "ФИО"))
        self.dateLabel.setText(_translate("Dialog", "Дата рождения"))
        self.dateEdit.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy"))
        self.sexLabel.setText(_translate("Dialog", "Пол"))
        self.weightLabel.setText(_translate("Dialog", "Категория"))
        self.categoryLabel.setText(_translate("Dialog", "Разряд"))
        self.trainerLabel.setText(_translate("Dialog", "Тренер"))
        self.regionLabel.setText(_translate("Dialog", "Регион"))
        self.cityLabel.setText(_translate("Dialog", "Город"))
        self.clubLabel.setText(_translate("Dialog", "Клуб"))
        self.cancelButton.setText(_translate("Dialog", "Отменить"))
        self.addButton.setText(_translate("Dialog", "Добавить"))
        self.updateButton.setText(_translate("Dialog", "Обновить"))

