# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meet.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(607, 723)
        self.start = QtWidgets.QLabel(Dialog)
        self.start.setGeometry(QtCore.QRect(10, 70, 59, 24))
        self.start.setObjectName("start")
        self.startDate = QtWidgets.QDateEdit(Dialog)
        self.startDate.setGeometry(QtCore.QRect(70, 70, 110, 24))
        self.startDate.setDate(QtCore.QDate(2017, 1, 1))
        self.startDate.setObjectName("startDate")
        self.end = QtWidgets.QLabel(Dialog)
        self.end.setGeometry(QtCore.QRect(190, 70, 81, 24))
        self.end.setObjectName("end")
        self.endDate = QtWidgets.QDateEdit(Dialog)
        self.endDate.setGeometry(QtCore.QRect(270, 70, 110, 24))
        self.endDate.setDate(QtCore.QDate(2017, 1, 1))
        self.endDate.setObjectName("endDate")
        self.name = QtWidgets.QLabel(Dialog)
        self.name.setGeometry(QtCore.QRect(10, 10, 59, 24))
        self.name.setObjectName("name")
        self.nameEdit = QtWidgets.QLineEdit(Dialog)
        self.nameEdit.setGeometry(QtCore.QRect(80, 10, 511, 24))
        self.nameEdit.setObjectName("nameEdit")
        self.athletes = QtWidgets.QLabel(Dialog)
        self.athletes.setGeometry(QtCore.QRect(10, 130, 141, 16))
        self.athletes.setObjectName("athletes")
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(285, 220, 31, 24))
        self.addButton.setObjectName("addButton")
        self.removeButton = QtWidgets.QPushButton(Dialog)
        self.removeButton.setGeometry(QtCore.QRect(285, 260, 31, 24))
        self.removeButton.setObjectName("removeButton")
        self.members = QtWidgets.QLabel(Dialog)
        self.members.setGeometry(QtCore.QRect(325, 130, 131, 16))
        self.members.setObjectName("members")
        self.meetCount = QtWidgets.QLabel(Dialog)
        self.meetCount.setGeometry(QtCore.QRect(390, 70, 121, 24))
        self.meetCount.setObjectName("meetCount")
        self.meetCountEdit = QtWidgets.QLineEdit(Dialog)
        self.meetCountEdit.setGeometry(QtCore.QRect(510, 70, 81, 24))
        self.meetCountEdit.setObjectName("meetCountEdit")
        self.sortitionButton = QtWidgets.QPushButton(Dialog)
        self.sortitionButton.setGeometry(QtCore.QRect(490, 360, 100, 24))
        self.sortitionButton.setObjectName("sortitionButton")
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setGeometry(QtCore.QRect(492, 690, 100, 24))
        self.cancel.setObjectName("cancel")
        self.athletesList = QtWidgets.QListWidget(Dialog)
        self.athletesList.setGeometry(QtCore.QRect(10, 150, 266, 201))
        self.athletesList.setObjectName("athletesList")
        self.membersList = QtWidgets.QListWidget(Dialog)
        self.membersList.setGeometry(QtCore.QRect(325, 150, 266, 201))
        self.membersList.setObjectName("membersList")
        self.city = QtWidgets.QLabel(Dialog)
        self.city.setGeometry(QtCore.QRect(10, 40, 131, 24))
        self.city.setObjectName("city")
        self.cityEdit = QtWidgets.QLineEdit(Dialog)
        self.cityEdit.setGeometry(QtCore.QRect(140, 40, 451, 24))
        self.cityEdit.setObjectName("cityEdit")
        self.main_referee = QtWidgets.QLabel(Dialog)
        self.main_referee.setGeometry(QtCore.QRect(10, 400, 101, 24))
        self.main_referee.setObjectName("main_referee")
        self.main_clerk = QtWidgets.QLabel(Dialog)
        self.main_clerk.setGeometry(QtCore.QRect(10, 430, 131, 24))
        self.main_clerk.setObjectName("main_clerk")
        self.mainrefCBox = QtWidgets.QComboBox(Dialog)
        self.mainrefCBox.setGeometry(QtCore.QRect(120, 400, 471, 24))
        self.mainrefCBox.setObjectName("mainrefCBox")
        self.mainclerkCBox = QtWidgets.QComboBox(Dialog)
        self.mainclerkCBox.setGeometry(QtCore.QRect(140, 430, 451, 24))
        self.mainclerkCBox.setObjectName("mainclerkCBox")
        self.refList = QtWidgets.QListWidget(Dialog)
        self.refList.setGeometry(QtCore.QRect(10, 480, 266, 201))
        self.refList.setObjectName("refList")
        self.refereeList = QtWidgets.QLabel(Dialog)
        self.refereeList.setGeometry(QtCore.QRect(10, 460, 91, 16))
        self.refereeList.setObjectName("refereeList")
        self.refColList = QtWidgets.QListWidget(Dialog)
        self.refColList.setGeometry(QtCore.QRect(325, 480, 266, 201))
        self.refColList.setObjectName("refColList")
        self.refereeCol = QtWidgets.QLabel(Dialog)
        self.refereeCol.setGeometry(QtCore.QRect(325, 460, 141, 16))
        self.refereeCol.setObjectName("refereeCol")
        self.raddButton = QtWidgets.QPushButton(Dialog)
        self.raddButton.setGeometry(QtCore.QRect(285, 560, 31, 24))
        self.raddButton.setObjectName("raddButton")
        self.rremoveButton = QtWidgets.QPushButton(Dialog)
        self.rremoveButton.setGeometry(QtCore.QRect(285, 600, 31, 24))
        self.rremoveButton.setObjectName("rremoveButton")
        self.wsortitionButton = QtWidgets.QPushButton(Dialog)
        self.wsortitionButton.setEnabled(True)
        self.wsortitionButton.setGeometry(QtCore.QRect(360, 690, 121, 24))
        self.wsortitionButton.setAutoDefault(True)
        self.wsortitionButton.setDefault(False)
        self.wsortitionButton.setFlat(False)
        self.wsortitionButton.setObjectName("wsortitionButton")
        self.divrings = QtWidgets.QCheckBox(Dialog)
        self.divrings.setGeometry(QtCore.QRect(390, 100, 201, 24))
        self.divrings.setObjectName("divrings")
        self.weightcatCBox = QtWidgets.QComboBox(Dialog)
        self.weightcatCBox.setGeometry(QtCore.QRect(150, 100, 231, 24))
        self.weightcatCBox.setObjectName("weightcatCBox")
        self.weigthcat = QtWidgets.QLabel(Dialog)
        self.weigthcat.setGeometry(QtCore.QRect(10, 100, 131, 24))
        self.weigthcat.setObjectName("weigthcat")
        self.round = QtWidgets.QLabel(Dialog)
        self.round.setGeometry(QtCore.QRect(220, 130, 61, 16))
        self.round.setObjectName("round")
        self.stage = QtWidgets.QLabel(Dialog)
        self.stage.setGeometry(QtCore.QRect(490, 130, 101, 16))
        self.stage.setObjectName("stage")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.nameEdit, self.cityEdit)
        Dialog.setTabOrder(self.cityEdit, self.startDate)
        Dialog.setTabOrder(self.startDate, self.endDate)
        Dialog.setTabOrder(self.endDate, self.meetCountEdit)
        Dialog.setTabOrder(self.meetCountEdit, self.weightcatCBox)
        Dialog.setTabOrder(self.weightcatCBox, self.divrings)
        Dialog.setTabOrder(self.divrings, self.athletesList)
        Dialog.setTabOrder(self.athletesList, self.addButton)
        Dialog.setTabOrder(self.addButton, self.removeButton)
        Dialog.setTabOrder(self.removeButton, self.membersList)
        Dialog.setTabOrder(self.membersList, self.sortitionButton)
        Dialog.setTabOrder(self.sortitionButton, self.mainrefCBox)
        Dialog.setTabOrder(self.mainrefCBox, self.mainclerkCBox)
        Dialog.setTabOrder(self.mainclerkCBox, self.refList)
        Dialog.setTabOrder(self.refList, self.raddButton)
        Dialog.setTabOrder(self.raddButton, self.rremoveButton)
        Dialog.setTabOrder(self.rremoveButton, self.refColList)
        Dialog.setTabOrder(self.refColList, self.wsortitionButton)
        Dialog.setTabOrder(self.wsortitionButton, self.cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Создание соревнования"))
        self.start.setText(_translate("Dialog", "Начало"))
        self.startDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy"))
        self.end.setText(_translate("Dialog", "Окончание"))
        self.endDate.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy"))
        self.name.setText(_translate("Dialog", "Название"))
        self.athletes.setText(_translate("Dialog", "Список спортсменов"))
        self.addButton.setText(_translate("Dialog", ">>"))
        self.removeButton.setText(_translate("Dialog", "<<"))
        self.members.setText(_translate("Dialog", "Список участников"))
        self.meetCount.setText(_translate("Dialog", "Число боев в день"))
        self.sortitionButton.setText(_translate("Dialog", "Жеребьевка"))
        self.cancel.setText(_translate("Dialog", "Отмена"))
        self.city.setText(_translate("Dialog", "Место проведения"))
        self.main_referee.setText(_translate("Dialog", "Главный судья"))
        self.main_clerk.setText(_translate("Dialog", "Главный секретарь"))
        self.refereeList.setText(_translate("Dialog", "Список судей"))
        self.refereeCol.setText(_translate("Dialog", "Судейская коллегия"))
        self.raddButton.setText(_translate("Dialog", ">>"))
        self.rremoveButton.setText(_translate("Dialog", "<<"))
        self.wsortitionButton.setText(_translate("Dialog", "Без жеребьевки"))
        self.divrings.setText(_translate("Dialog", "Разбивать по рингам"))
        self.weigthcat.setText(_translate("Dialog", "Весовая категория"))
        self.round.setText(_translate("Dialog", "раунд"))
        self.stage.setText(_translate("Dialog", "стадия"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

